version: "3.8"

services:
  mlflow:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/data/mlflow/
    ports:
      - 5123:5123
    networks: 
      - mlops
    env_file:
      - mlflow.env

networks:
  mlops:
    external: true
    name: mlops